sudo: required
services:
    - docker
env:
    global:
        - GIT_SHA=$(git rev-parse HEAD)
        - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
    - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d
    - curl https://sdk.cloud.google.com | bash > /dev/null;
    - source $HOME/google-cloud-sdk/path.bash.inc
    - gcloud components update kubectl
    - gcloud auth activate-service-account --key-file service-account.json
    - gcloud config set project k8s-multi-container-test
    - gcloud config set compute/zone us-central1-a  # adjust zone dep on k8s cluster zone
    - gcloud container clusters get-credentials k8s-multi-container-test-cluster-1 # adjust cluster name as appropriate
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker build -t i11f2jz8e7/react-test -f ./frontend/Dockerfile.dev ./frontend
scripts:
    - docker run i11f2jz8e7/react-test npm test -- --coverage
deploy:
    provider: script
    script: bash ./deploy.sh
    on:
        branch: master